apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foodomain
    collection: example
    layer: domain
  name: foodomain-deployment
  namespace: con
spec:
  selector:
    matchLabels:
      app: foodomain
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: foodomain
        collection: audit
        layer: domain
    spec:
      containers:
      - image: docker.pkg.github.com/ardove/argocd-example-apps/foodomain:1.0.0
        name: foodomain
        ports:
          - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development

